twig:
    paths:            [ '%kernel.project_dir%/templates' ]
    debug:            '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        main_brand_title:                   '%env(string:MAIN_BRAND_TITLE)%'
        main_brand_url:                     '%env(string:MAIN_BRAND_URL)%'
        main_brand_email:                   '%env(string:MAIN_BRAND_EMAIL)%'
        main_brand_assistance_phone_number: '%env(string:MAIN_BRAND_ASSISTANCE_PHONE_NUMBER)%'
        admin_tag_version:                  'v0.0.04'

services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    Twig\Extra\Intl\IntlExtension: ~
