sylius_shop:
    resource: '@SyliusShopBundle/Resources/config/routing.yml'
    prefix:
        en:    '/en'
        en_UK: '/en'
        en_US: '/en'
        es:    '/es'
        es_ES: '/es'
    requirements:
        _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$

sylius_shop_payum:
    resource: '@SyliusShopBundle/Resources/config/routing/payum.yml'

sylius_shop_default_locale:
    path:    /
    methods: [ GET ]
    defaults:
        _controller: sylius.controller.shop.locale_switch:switchAction
