monolog:
    handlers:
        main:
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            type:  stream
            level: debug
        firephp:
            type:  firephp
            level: info
