swiftmailer:
    disable_delivery: false
    delivery_addresses: [ '%env(string:MAILER_DEV_DELIVERY_ADDRESS)%' ]
    logging: true
    spool:
        type: file
        path: '%kernel.cache_dir%/spool'
