monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            path:  '%kernel.logs_dir%/%kernel.environment%.log'
            type:  stream
            level: debug
