---
- hosts: s6
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/vars/config.yml"
  tasks:
    - name: copy remote uploads directory to local
      synchronize:
        mode: pull
        recursive: yes
        perms: yes
        times: yes
        src: "{{ vhost_base_dir_prod }}/{{ mysql_db_remote_name_prod }}/shared/web/uploads"
        dest: "{{ playbook_dir }}/../../public"
    - name: fix ownership in downloaded files locally
      delegate_to: mother
      file:
        path: "{{ playbook_dir }}/../../public/uploads"
        recurse: yes
        follow: yes
        owner: "{{ local_system_user }}"
        group: "{{ local_system_group }}"
